tmp

diff --git a/s3/bash-scripts/delete-bucket b/s3/bash-scripts/delete-bucket
--- a/s3/bash-scripts/delete-bucket
+++ b/s3/bash-scripts/delete-bucket
@@ -1,1 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "Bucket name is required"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+
+# Delete bucket
+aws s3api delete-bucket \
+    --bucket "$BUCKET_NAME" \
+    --output text
+
+if [ $? -eq 0 ]; then
+    echo "Bucket $BUCKET_NAME deleted successfully."
+else
+    echo "Failed to delete bucket $BUCKET_NAME"
+fi
diff --git a/s3/bash-scripts/list-object b/s3/bash-scripts/list-object
--- a/s3/bash-scripts/list-object
+++ b/s3/bash-scripts/list-object
@@ -1,1 +1,18 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+
+aws s3api list-objects-v2 \
+--bucket $BUCKET_NAME
+
+if [ $? -eq 0 ]; then
+    echo "List object from $BUCKET_NAME"
+else
+    echo "Failed to list object from bucket $BUCKET_NAME"
+fi
